### ISSUE TITLE
Configure git

### ISSUE THREAD

**Issue by carolclark** [cebcar/recent-DevOps#12]
Configure git #12

- use iTerm

- see [w3c: Git config](https://www.w3docs.com/learn-git/git-config.html#merge-tools-of-git-config-20)

- [ ] perform git merge with IDE #13
- [ ] alias file for git commands #24

then: establilsh Z Shell #21
- [ ] script git configuration #18
