### ISSUE TITLE
merge deprecated folders content

### ISSUE THREAD

**Issue by carolclark** [cebcar/recent-DevOps#14]
merge deprecated folders content #14

=== from docs to intended folders #27

### All Existing /docs Content is in Intended Files and Folders
- folders starter-wiki, from-Notes-app, dev-proj are deprecated
  - organized before documentation organization was standardized
  - file format not consistent<br/><br/>

- [ ] remove extra characters from 'Notes' issues #19

- [ ] sort deprecated docs folder content #20

- [ ] merge in content from deprecations #14

===

- folders starter-wiki, from-Notes-app, dev-proj are deprecated
  - they were organized differently before documentation organization was standardized
  - their file formats are not consistent

### merge and format into target documents
merge content from starter-wiki, from-Notes-app, dev-proj into permanent /docs folders

- [ ] remove extra characters from 'Notes' issues #19
- [ ] sort deprecated docs folder content #20
- [ ] recover deprecated docs/ content #37
  - move content from deprecated content folder to main documentation
