### ISSUE TITLE
sort deprecated docs folder content

### ISSUE THREAD

**Issue by carolclark** [cebcar/recent-DevOps#20]
sort deprecated docs folder content #20

=== from docs to intended folders #27

### All Existing /docs Content is in Intended Files and Folders
- folders starter-wiki, from-Notes-app, dev-proj are deprecated
  - organized before documentation organization was standardized
  - file format not consistent<br/><br/>

- [ ] remove extra characters from 'Notes' issues #19

- [ ] sort deprecated docs folder content #20

- [ ] merge in content from deprecations #14

===
collect legacy docs information

reorganize content from the set of legacy documents into temporary documents that contain collected info
search/examine all legacy documents currently included in project for relevant information<br/><br/>

Targets:

filenames: legacy-docs/&lt;folder&gt;/[for-]&lt;filename&gt;; prefix with "for-" if file already exists<br/><br/>

Sources:

- dev-proj/* (1)
- [ ] dev-proj/Iter0-planning.md
- from-notes-app/* (13)
- [ ] from-Notes-app/Changes-from-DD#76-support-IDE-Tasks.md
- [ ] from-Notes-app/Tidbits.md
- [ ] from-Notes-app/MultitaskingInIOS.md
- [ ] from-Notes-app/vcs_copy.xml
- [ ] from-Notes-app/InstallationNotes.md
- [ ] from-Notes-app/macos-UI-keyboard-access.md
- [ ] from-Notes-app/ReleaseTag.md
- [ ] from-Notes-app/Sketch-get-AppCleaner.md
- [ ] from-Notes-app/GitHub-IJ-JBT.md
- [ ] from-Notes-app/BrokenBranch(es).md
- [ ] from-Notes-app/RoadMapNotes.md
- [ ] from-Notes-app/settings.md
- [ ] from-Notes-app/MoveToZsh.md- starter-wiki/* (27)
- starter-wiki (27)
- [ ] starter-wiki/Up-and-Running-(Epic).md
- [ ] starter-wiki/acTerm.zsh
- [ ] starter-wiki/starter_gitignore.txt
- [ ] starter-wiki/TL_macos.md
- [ ] starter-wiki/Tool-Template.md
- [ ] starter-wiki/sc_GitHub-Project.md
- [ ] starter-wiki/TL_Mail.md
- [ ] starter-wiki/LastPass.md
- [ ] starter-wiki/GitHubProject-Filter.md.md
- [ ] starter-wiki/sc_AppCode.md
- [ ] starter-wiki/Catalina-(Epic).md
- [ ] starter-wiki/Git.md
- [ ] starter-wiki/Git-Workflows.md
- [ ] starter-wiki/getting_started.md.md
- [ ] starter-wiki/gitignore_start.txt
- [ ] starter-wiki/Home.md
- [ ] starter-wiki/ZZDO#2x:-Add-Project-Board-(Spike---closed).md
- [ ] starter-wiki/RestAPI.md.md
- [ ] starter-wiki/Old-System-Installation.md
- [ ] starter-wiki/MyReadingList.md
- [ ] starter-wiki/ZZDO#3:-start-DevOps-docs-(docs).md
- [ ] starter-wiki/notes.md.md
- [ ] starter-wiki/Working.md
- [ ] starter-wiki/gitignore.md
- [ ] starter-wiki/DX_BasicSettings.md
- [ ] starter-wiki/HubRing.html.md
- [ ] starter-wiki/DevOps_FirstIssues.md
