### ISSUE TITLE
docs to intended folders

### ISSUE THREAD

**Issue by carolclark** [cebcar/recent-DevOps#27]
docs to intended folders #27

### All Existing /docs Content is in Intended Files and Folders
- folders starter-wiki, from-Notes-app, dev-proj are deprecated
  - organized before documentation organization was standardized
  - file format not consistent<br/><br/>

- [ ] remove extra characters from 'Notes' issues #19

- [ ] sort deprecated docs folder content #20

- [ ] merge in content from deprecations #14
