### ISSUE TITLE
establish Z shell

### ISSUE THREAD

**Issue by carolclark** [cebcar/recent-DevOps#31]
establish Z shell environment #31

[Tentative steps](./#tentative-steps)
#### Shells Status

- CLI:
  - Previously: Bash, as provided by Apple for Terminal
  - Currently: Z Shell, as provided by Apple since Catalina<br/><br/>

- Scripting:
  - Previously: mostly, Bash (initially), Korn Shell (more recently)
  - Future: Z Shell<br/><br/>

### configure IntelliJ Shell Scripting
- [IntelliJ IDEA: Shell Scripts](https://www.jetbrains.com/help/idea/shell-scripts.html)
  
  
    - check out recommended External Tools; probably install now or plan to add later<br/><br/>

### configure Z Shell
[The definitive iTerm2 & Oh-my-ZSH Setup on macOS](https://blog.larsbehrenberg.com/the-definitive-iterm2-and-oh-my-zsh-setup-on-macos)

#### Tentative steps
- [ ] tool ZUnit
- [ ] install ZUnit
- [ ] create testZShell
  - models testing for shell scripts
  - provide environment for demonstration and experimentation with Z Shell functionality
  - start policy to provide 'undo' script for configuration actions for testing
- [ ] configure Z Shell
  - script to undo configuration actions for testing

====
- [ ] learn Z Shell Penguins#17
- [ ] perform git merge with IDE #13

require: tool iTerm #35

- [ ] Z Shell setup #43
- [ ] Configure git #12
- [ ] alias file for git commands #24

- [ ] script git configuration #18
