### ISSUE TITLE
collect legacy docs and issues

### ISSUE THREAD

**Issue by carolclark** [cebcar/recent-DevOps#37]
collect legacy docs and issues #37

*repository DevSupport was last changed 9 Nov 2019*

#### DevOps content created before project made IntelliJ documentation editing available
  - docs now appear in docs/ subfolders by content source<br/><br/>
- [ ] merge deprecated folders content #14

#### review and collect content @ github/cebcar
- [ ] recover docs and issues from github/cebcar repos #28

#### review and collect content @ github/carolclark
- [ ] recover docs and issues from github/carolclark repos (DevSupport, Accessor, Punkin) #38
