### ISSUE TITLE
UML Diagramming_

### ISSUE THREAD

**Issue by carolclark** [cebcar/recent-DevOps#5]
UML Diagramming #5

*add capability to include UML Diagrams in technical documentation*
   *because* ***Carol needs pictures***

### UML Information
- *[UML Notation Tutorial: Symbol with Examples](https://www.guru99.com/uml-notation-symbol.html)
  - we really like the organization of this one; use it as a structure for our own documentation
    - it emphasizes what you can do in simple terms, as opposed to organization by diagram type in detail
    - it documents UML as opposed to PlantUML, so we will have to develop the diagrams as we go
- [UML Tutorial](https://www.tutorialspoint.com/uml/index.htm) from TutorialsPoint
<br/>
- [Allen Holub’s UML Quick Reference](https://holub.com/uml/)
  - excellent reference
  - more detail than we need
  - do not know that all details are supported by UML diagramming<br/><br/>

### Select Rendering Tool
- [x] Select Rendering Tool
  - IntelliJ has a plugins for both PlantUML and Mermaid
  - PlantUML
    - very widely used
    - good documentation
    - not attractive, but custom styling available
  - Mermaid
    - docs: [Use Mermaid syntax to create diagrams](https://www.diagrams.net/blog/mermaid-diagrams)
    - attractive
    - documentation  difficult to understand
      - usually just recommends using their Live Editor to experiment from a sample
  -  selected PlantUML

### PlantUML References
- [PlantUML in a Nutshell](https://plantuml.com)
- [Tutorials](https://www.augmentedmind.de/2021/01/)
  - Diagrams: [PlantUML Tutorial: Diagrams as Code](https://www.augmentedmind.de/2021/01/03/plantuml-tutorial-diagrams-as-code/)
  - Styles: [PlantUML Tutorial: Layouts and Styles](https://www.augmentedmind.de/2021/01/17/plantuml-layout-tutorial-styles/)
  - PlantUML Tool: [PlantUML Tutorial: Advanced Features](https://www.augmentedmind.de/2021/01/31/plantuml-advanced-features/)

#### Styling
- *stylesheet starter at [PlantUML with Style -- How I do PlantUML](https://gist.github.com/jerieljan/4c82515ff5f2b2e4dd5122d354a82b7e)
  - provides structure with flexibility
  - has system for collapsing MANY available PlantUML colors to 3
  - uses fonts we do not have
- also available ready to use stylesheet at [RedDress-PlantUML](https://github.com/Drakemor/RedDress-PlantUML)
  - select from multiple colors, light/dark
  - but we find those colors, especially for dark styles, visually confusing

### So...

- [ ] adopt PlantUML #15

- [ ] create some UML diagrams
- start with default styles
##### document Tuxedo.md includes simple drawing (*Object drawing?*) of Tuxedo project
- initial [Object](https://plantuml.com/object-diagram) drawing of Tuxedo ZenHub project
  - Workspace Tuxedo, with Roadmap and Board
  - RepoProjects for included repositories
##### dependencies among issues/epics
- Gantt chart for dependencies on Roadmap (could be needed soon)<br/><br/>

- [ ] add UML stylesheet #16
