### ISSUE TITLE
Tools files and template

### ISSUE THREAD

**Issue by carolclark** [cebcar/recent-DevOps#7]
Tools files and template #7

## Tool Profile
- Tool files include some standard information about the tool's version, licence, source, documentation, ...
- standard information included in the Tools file header includes  Configuration information, which can get long
- Alternatives Considered is also being added; could also be long, moving the main "Using ..." section even farther down

- so: change the header section at the top to a Profile section at the end

### *add IntelliJ template for Tool file with profile*
- [ ] add IntelliJ template for Tool file with profile
- can use generic filename (eg, Drawing Tool) during evaluation; change to name of tool selected (eg. Figma)

### *standardize and update the Tool header format*
- document entity 'tool' and its standard file format

### *refactor: standardize Tool header format*
plan and document revised outline for Tools files
  - document at entities/tools
  - changes:
    - get basic profile format from file GitHub.md
    - move current profile information to end of file
    - add Alternatives Considered
    - change "Shortcuts" to "Keymap"<br/><br/>

  - change heading "&lt;toolname&gt;" to "&lt;toolname&gt; Profile"
  - move Profile section to the end of the file
  - since "Using &lt;toolname&gt;" is now at the top, omit the word "Using ..."<br/><br/>

### add link to the "&lt;toolname&gt; Profile"
- right-aligned, near top heading

### IntelliJ template for tools file
- [ ] create IntelliJ template for new tools files

- old outline:
#set( $h1 = '#' )
#set( $h2 = '##' )
#set( $h3 = ‘###’)
$h1 ${NAME}
$h2 Tool ${NAME}
  ${TOOLTYPE} @ ${LOCATION}
  *${BLURB}*
  **Version**: ${VERSION}
  **Source**: ${SOURCE}
  **License**: ${LICENSE}
  **Critical Data**: ${CRITICAL-DATA-LOCATION}
  **Source**: ${SOURCE} # where we got it from
  **Installation**: %
  **Documentation**: %
$h3 ${NAME} **Configuration**: %
$h3 ${NAME} **Customization &amp; Automation**: %
$h3 ${NAME} **Shortcuts**: %

$h2 Using ${NAME}

#### javascript to repeat tool taglines
- [ ] ***javascript to repeat tool taglines***
  - see [Embed javascript in markdown](https://stackoverflow.com/questions/2754391/embed-javascript-in-markdown)
